ACTIVIDADES = [
    {"actividad": "Codificación", "tipo_medicion": "cantidad", "unidad_base": "pares"},
    {"actividad": "Sacar Basura", "tipo_medicion": "cumplimiento", "unidad_base": None},
    {"actividad": "Recepción de Guía (Revisión)", "tipo_medicion": "cumplimiento", "unidad_base": None},
    {"actividad": "Visita de Tienda (Atención)", "tipo_medicion": "turno", "unidad_base": None},
    {"actividad": "Apoyo a Tienda", "tipo_medicion": "turno", "unidad_base": None},
    {"actividad": "Limpieza", "tipo_medicion": "cumplimiento", "unidad_base": None},
    {"actividad": "Apoyo Inter-Area", "tipo_medicion": "turno", "unidad_base": None},
    {"actividad": "Transporte de Bulto (En grupo)", "tipo_medicion": "cumplimiento", "unidad_base": None},
    {"actividad": "Transporte de Bulto (Solo)", "tipo_medicion": "cumplimiento", "unidad_base": None},
    {"actividad": "Transporte de Bulto (Montacarga)", "tipo_medicion": "cumplimiento", "unidad_base": None},
    {"actividad": "Recepción de Mercadería (Descargar)", "tipo_medicion": "cantidad", "unidad_base": "contenedores"},
    {"actividad": "Reposición", "tipo_medicion": "turno", "unidad_base": None},
    {"actividad": "Clasificación", "tipo_medicion": "turno", "unidad_base": None},
    {"actividad": "Cuadre Lote (Supervisión)", "tipo_medicion": "cumplimiento", "unidad_base": None},
    {"actividad": "Cuadre Lote (Impresión Códigos)", "tipo_medicion": "cumplimiento", "unidad_base": None},
    {"actividad": "Pistoleado y Embalado (Despacho)", "tipo_medicion": "tiempo", "unidad_base": "minutos"},
    {"actividad": "Envío Nuevo", "tipo_medicion": "tiempo", "unidad_base": "minutos"},
    {"actividad": "Micro Inventario", "tipo_medicion": "cantidad", "unidad_base": "pares"},
    {"actividad": "Levantar Información (Merma)", "tipo_medicion": "cantidad", "unidad_base": "cajas"},
    {"actividad": "Pedido por Mayor", "tipo_medicion": "cumplimiento", "unidad_base": None},
]
