-- Incidencias registradas por el jefe de equipo.

create table if not exists public.incidentes (
  id bigint generated by default as identity primary key,
  turno text not null,
  nombre text not null,
  tarea_id bigint not null,
  tarea_nombre text not null,
  tienda_id bigint not null,
  numero_guia text not null,
  observacion text,
  tipo_error text not null,
  created_by bigint not null,
  created_at timestamptz not null default now(),
  usuario_id bigint not null
);

alter table public.incidentes
  add column if not exists usuario_id bigint;

update public.incidentes i
set
  turno = coalesce(nullif(btrim(i.turno), ''), 'Sin turno'),
  nombre = coalesce(
    nullif(btrim(i.nombre), ''),
    (select coalesce(u.nombre, u.email) from public.usuarios u where u.id = coalesce(i.usuario_id, i.created_by)),
    'Usuario sin nombre'
  ),
  tarea_nombre = coalesce(
    nullif(btrim(i.tarea_nombre), ''),
    (select t.nombre from public.tareas t where t.id = i.tarea_id),
    'Tarea ' || i.tarea_id::text
  ),
  numero_guia = coalesce(nullif(btrim(i.numero_guia), ''), 'SIN-GUIA'),
  tipo_error = coalesce(nullif(btrim(i.tipo_error), ''), 'SIN TIPO'),
  created_by = coalesce(i.created_by, i.usuario_id),
  usuario_id = coalesce(
    i.usuario_id,
    (select u.id from public.usuarios u where lower(btrim(u.nombre)) = lower(btrim(i.nombre)) order by u.id limit 1),
    i.created_by
  ),
  created_at = coalesce(i.created_at, now());

do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.incidentes'::regclass
      and contype = 'c'
  loop
    execute format('alter table public.incidentes drop constraint if exists %I', constraint_record.conname);
  end loop;
end $$;

alter table public.incidentes
  alter column turno set not null,
  alter column nombre set not null,
  alter column tarea_id set not null,
  alter column tarea_nombre set not null,
  alter column tienda_id set not null,
  alter column numero_guia set not null,
  alter column tipo_error set not null,
  alter column created_by set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column usuario_id set not null;

create index if not exists idx_incidentes_tienda_id on public.incidentes(tienda_id);
create index if not exists idx_incidentes_tarea_id on public.incidentes(tarea_id);
create index if not exists idx_incidentes_usuario_id on public.incidentes(usuario_id);
create index if not exists idx_incidentes_created_at on public.incidentes(created_at desc);

grant select, insert, update, delete on public.incidentes to service_role;
grant usage, select on sequence public.incidentes_id_seq to service_role;

notify pgrst, 'reload schema';
