-- Catalogo de lotes de mercaderia. La tabla ya existe en produccion (creada
-- manualmente); este archivo documenta su estructura real en el repo para
-- que quede junto al resto de migraciones y sea reproducible en otro
-- entorno. create/alter usan "if not exists" para no romper nada si ya
-- esta creada.

begin;

create table if not exists public.lotes (
  id bigint generated by default as identity primary key,
  codigo_lote varchar not null,
  cantidad_lote integer not null,
  marca_id bigint not null references public.marcas(id) on delete restrict,
  fecha_ingreso date not null,
  proveedor varchar not null,
  usuario_id bigint not null references public.usuarios(id) on delete restrict
);

alter table public.lotes
  drop constraint if exists lotes_cantidad_lote_check;
alter table public.lotes
  add constraint lotes_cantidad_lote_check check (cantidad_lote >= 0);

create index if not exists idx_lotes_marca on public.lotes(marca_id);
create index if not exists idx_lotes_usuario on public.lotes(usuario_id);

grant select, insert, update, delete on public.lotes to service_role;
grant usage, select on sequence public.lotes_id_seq to service_role;

notify pgrst, 'reload schema';

commit;
