-- Registro de guias de salida importadas desde los reportes "Salidas AAAA
-- mes.xlsx". Cada guia se identifica por su codigo (columna "TDA ORIGEN" del
-- reporte) y se guarda una sola vez: importar el mismo archivo (o uno con
-- guias repetidas) no crea duplicados gracias al unique en "codigo".

begin;

create table if not exists public.guias (
  id bigint generated by default as identity primary key,
  codigo varchar not null,
  fecha date not null,
  archivo_origen varchar,
  created_at timestamptz not null default now()
);

alter table public.guias
  drop constraint if exists guias_codigo_key;
alter table public.guias
  add constraint guias_codigo_key unique (codigo);

create index if not exists idx_guias_fecha on public.guias(fecha);

grant select, insert, update, delete on public.guias to service_role;
grant usage, select on sequence public.guias_id_seq to service_role;

notify pgrst, 'reload schema';

commit;
