-- Detalle linea por linea de cada guia (un producto despachado por fila en
-- el reporte "Salidas AAAA mes.xlsx"). "guias" guarda un resumen por guia
-- (codigo + fecha); esta tabla guarda cada producto de esa guia para no
-- perder informacion al importar. "datos" conserva la fila completa tal
-- como viene en el Excel (clave = encabezado de columna, valor = celda),
-- porque varias columnas del reporte no tienen un significado 100% fijo y
-- preferimos no inventarles nombres.
--
-- El dedupe al reimportar es por (codigo_guia, codigo_item). "codigo_item"
-- no es un codigo de columna del reporte (varios encabezados del Excel no
-- coinciden con su propio dato, asi que no son confiables): es una huella
-- (hash) del contenido completo de la fila, calculada al importar, que
-- identifica esa linea dentro de su guia.

begin;

create table if not exists public.guias_items (
  id bigint generated by default as identity primary key,
  codigo_guia varchar not null references public.guias(codigo) on delete cascade,
  codigo_item varchar not null,
  fecha date not null,
  datos jsonb not null default '{}'::jsonb,
  archivo_origen varchar,
  created_at timestamptz not null default now()
);

alter table public.guias_items
  drop constraint if exists guias_items_guia_item_key;
alter table public.guias_items
  add constraint guias_items_guia_item_key unique (codigo_guia, codigo_item);

create index if not exists idx_guias_items_fecha on public.guias_items(fecha);
create index if not exists idx_guias_items_codigo_guia on public.guias_items(codigo_guia);

grant select, insert, update, delete on public.guias_items to service_role;
grant usage, select on sequence public.guias_items_id_seq to service_role;

notify pgrst, 'reload schema';

commit;
